### ISSUE TITLE
Number of Downloadable Items are not being saved

### ISSUE THREAD

**Issue by T-prog3** [TumblThreeApp/TumblThree#497] opened 2023-11-18 20:31 UTC
When adding a blog to TumblThree it start to evaluate ```Number of Downloadable Items``` but if i then exit the software and start again this number becomes empty.

**Comment by johnflint1985** [comment] 2023-12-09 05:19
Same here. Unlee the number of downloads are specified while adding the blog it is being lost once you tirn off the programm and once it is open the number is no longer there. More to that - program after that does not download the correct number of pictures inside, since it looses the original count of them.

**Comment by thomas694** [comment] 2023-12-11 23:32
The saving of the numbers will be fixed in the next version.
But the numbers are statistics only, so I doubt that it's the cause for any missing downloads.

**Comment by johnflint1985** [comment] 2023-12-12 23:38
I've tried it both ways - without a count and with the right count. Without a count - program downloads only a fraction of the total number of pictures. With the count present - program downloads everything and then some. Also I noticed that if you populate the list of blogs in the program using your old Export Blog text file the count of the pictures inside the blog, disappears after you turn the program off. And if you manually add one blog after one inside the program, the count stays the next time you are opening it.

**Comment by thomas694** [comment] 2023-12-16 20:19
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Closed by thomas694** 2023-12-16 20:19 UTC

**Comment by johnflint1985** [comment] 2023-12-17 19:12
Thank you very much Thomas! So far as I tested the new version the issue is fixed. Thank you for that. I will make a list of other things that I've noticed or wish to be a little different with the main issue so far SVC files are not downloading at all or the amout of files is not the same as in the blog. Is this an authification issue or something else, I have no idea. Anyways - thank you again
