### ISSUE TITLE
downloaded_media_files metadata is missing for "text" posts on hidden blogs

### ISSUE THREAD

**Issue by jacob-pro** [TumblThreeApp/TumblThree#414] opened 2022-12-26 01:38 UTC
**Describe the bug**

Hi again, thanks for implementing the `downloaded_media_files` feature 👍 

Unfortunately it seems for "text" posts where TumblThree has downloaded media from the HTML body - I was expecting that these files should be present in the `downloaded_media_files` array in the metadata - however the array is not present in the metadata.

`downloaded_media_files` seems to be present and working fine for "image" and "video" posts.

**Additional context**

Relates to:
- https://github.com/TumblThreeApp/TumblThree/discussions/286
- https://github.com/TumblThreeApp/TumblThree/commit/62373027d7b5d13d548be90104a5f265a719ed64

**Comment by jacob-pro** [comment] 2022-12-26 15:39
Ok, I think I've found the source of this bug @thomas694  - it happens on hidden blogs

The problem is that the `DownloadedFilenames` array is being cloned, and the downloads are written to the clone only:

https://github.com/TumblThreeApp/TumblThree/blob/e29d2880e9051e07012449265eb7acec83c702da/src/TumblThree/TumblThree.Applications/Crawler/TumblrHiddenCrawler.cs#L541-L544

https://github.com/TumblThreeApp/TumblThree/blob/a89a97d7b1a407d228b48b0c99d14a649fb92f45/src/TumblThree/TumblThree.Applications/Crawler/AbstractTumblrCrawler.cs#L372

**Comment by thomas694** [comment] 2022-12-31 01:19
Hi, I'll take a look the next days.

**Comment by thomas694** [comment] 2023-01-15 15:44
Yeah, you're right, the fastest fix is to change from deep copy to shallow copy in `ConvertTumblrApiJson`.

Actually this method was a shortcut to make the file rename functionality working for inline media too and use the methods and sub-methods with two different data objects. A less lazy way would have been to use a base class or interface which is passed through the methods.

**Comment by thomas694** [comment] 2023-01-23 20:24
The issue is fixed in version 2.10.0.

**Closed by thomas694** 2023-01-23 20:24 UTC
