### ISSUE TITLE
Error 429

### ISSUE THREAD

**Issue by johnflint1985** [TumblThreeApp/TumblThree#52] opened 2019-09-01 01:43 UTC
I have constantly en error 429 limit exceeded. no matter what I do it gives me the same error. I tried to make a number of API connections lower, but it didn't work

**Comment by Klimax** [comment] 2019-10-02 09:17
Pretty sure this is duplicate of this issue:
https://github.com/TumblThreeApp/TumblThree/issues/46

**Comment by johanneszab** [comment] 2020-01-25 18:34
I guess so too. Hence, please refer to the other issue.

**Closed by johanneszab** 2020-01-25 18:34 UTC
