### ISSUE TITLE
Problem to download tumblr hidden blog

### ISSUE THREAD

**Issue by lluisrvs** [TumblThreeApp/TumblThree#162] opened 2021-07-27 13:57 UTC
**Expected Behaviour**

Download Tumblr hidden blog

**Actual Behaviour**

Can't do it. I accept the Tumblr privacy consent but nothing happens. 

**Steps to Reproduce the Problem**

Detail the steps below to help us reproduce the problem you encountered.

  2. Click on '...'
  3. Scroll down to '...'

**Specifications**

TumblThree 2.0, Microsoft Windows 10 Home

**Comment by jimmyfi** [comment] 2021-07-31 11:45
I tried to bypass that by manually editing the blogs .tumblr file and set settings BlogType=1 and Online=1 then i was able to download hidden blog. but eventually they still went to being unable to download even if they still are online and hidden.

**Comment by thomas694** [comment] 2021-08-05 15:41
Do you have this problem with all your hidden blogs or only specific ones? Did it happen also before or only with version 2.0?
Can you see something in the log file (normally inside %LOCALAPPDATA%\TumblThree) when downloading this blog?

**Comment by lluisrvs** [comment] 2021-08-06 05:47
I tried to download several hidden blogs and all had problems. It happened before and after version 2.0.

**Comment by thomas694** [comment] 2021-08-06 15:05
Ok, so it's not a problem related to the new version.
Just to be sure. Did you also try to add new hidden blogs to your blog list? Or did you only try to download existing hidden blogs?
If not, please make backups of your blog files and download folder. Remove a hidden blog from the list, close the app and delete this blog's two files from the Index folder. Then try to add and download the hidden blog again.

**Comment by lluisrvs** [comment] 2021-08-06 22:16
I tried to add new hidden blogs. There is not any file of these hidden blogs to be deleted in the index folder.

**Comment by thomas694** [comment] 2021-08-06 23:03
Take one of your hidden blogs.
What are the file extensions of the blog's two files?
Inside the first file, what are the values for BlogType and OriginalBlogType?
Inside the _files file, what is the value for BlogType?

Do you see any error message near the end of TumblThree.log after trying to download a hidden blog?

**Comment by jimmyfi** [comment] 2021-08-07 09:36
I've noticed with new version as well that i have to edit index filexs to enable hidden blogs to be downloaded, 
Blog.tumblr
-> "BlogType": 1,
-> "Online": true,
-> "OriginalBlogType": 1,

and on blog_files.tumblr
"BlogType": 1,

Could it be that if the site says"sensitive material" that it is causing this behaviour?

**Comment by thomas694** [comment] 2021-08-07 21:09
Yes, Tumblr added at least two more ways how it opens blogs with sensitive content in the dashboard, hence TumblThree didn't know about that yet and failed to process these blogs correctly.

It should be fixed in the newest version.

Btw, I think it should be possible to make your mentioned changes through the UI ("blog type" in blog's settings and "Online" [check] through context menu).

**Comment by jimmyfi** [comment] 2021-08-08 08:38
Everything seems to work now with the new version for my part ) Thanks @thomas694

**Comment by thomas694** [comment] 2021-08-12 12:27
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Comment by UchuuStranger** [comment] 2022-11-29 04:34
May I ask to reopen this issue?

**Expected Behavior**

Download Tumblr hidden blog.

**Actual Behavior**

Can't do it. I logged in and accepted privacy consent (I think, more on that below) in TumblThree settings, but nothing happens. When the blog is first added, it appears to be online, but at the attempt to start the download the status changes to "offline", and "Error 1: The blog is offline" pops up.

**Describe the bug**
After running into this issue tried to download a regular blog and another hidden blog. Both downloaded successfully. At first I thought that the issue might be in the privacy consent, because when I clicked on it, it just opens the window with Tumblr home page rather than the consent pop-up, but the fact that another hidden blog with identical "for adults" warning downloaded successfully seems to indicate this is not the case, and the problem is somehow blog-specific. But the blog is definitely online, as I have no problems accessing its contents from Tumblr proper. In fact, once I manually edited the BlogType values in index folder files from 0 to 1 like @jimmyfi suggests, the blog downloads successfully, but if you delete the blog from the list and then add it again, it once again produces the "offline" error.

**Steps to Reproduce the Problem**
Since the problem appears to be blog-specific, I can disclose the blog that produced the error if necessary. The blog in question is somewhat NSFW, but it's not a porn blog. But if it's possible to troubleshoot on my end without resorting to that, can do that too.
1. Insert URL in "Enter URL:" field.
2. Click on "Add blog"
3. Select the blog in the list
4. Click on "Download"

**Specifications**

TumblThree 2.9.2.368, Microsoft Windows 10 Home

**Comment by thomas694** [comment] 2022-11-29 23:26
I checked a couple of hidden blogs, they all worked fine. Please send me the URL of the blog to my email (see profile) or paste it in the feedback dialog.

**Comment by thomas694** [comment] 2022-12-01 01:01
They changed the way the URL redirection is done, so TumblThree isn't able to recognize it properly.
It will be solved in the next version.
In the meantime you can just go to the blog settings and change the option "Crawler" to "Tumblr SVC" (instead of editing the file) after adding a new hidden blog.

**Comment by thomas694** [comment] 2022-12-18 18:01
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Closed by thomas694** 2022-12-18 18:01 UTC

**Comment by Littlesloths** [comment] 2025-02-28 15:30
See my other recent post. Currently, this is not working anymore.
see e.g. titten666.tumblr.com
