### ISSUE TITLE
latest update creates now 2 blogs: one empty and another one added "2" 

### ISSUE THREAD

**Issue by bloke90** [TumblThreeApp/TumblThree#178] opened 2021-11-01 21:52 UTC
Is this a feature or a bug?

**Comment by thomas694** [comment] 2021-11-01 22:44
Neither nor.
Please help us understand you better by providing us the steps you do and describe the outcome you see more detailed.

**Comment by bloke90** [comment] 2021-11-02 17:03
after your latetest update your app creates 2 files on my laptop: one with blog name, another one with blogname2

What happend? I use 2.4.1.210 with "auto-updater"

**Comment by thomas694** [comment] 2021-11-02 21:40
Did you tell that you added a new blog?
It creates two folders, as it's obviously too cautious. If you are sure the first one is empty, you can remove "_2" from the "download location" in the blog's settings before starting it.

Should be fixed in next version.

**Comment by bloke90** [comment] 2021-11-02 22:50
the 2 blog with the files is on same folder like I specify in the "download" location ...

**Comment by MikeMuc62** [comment] 2021-11-07 10:26
Hi I can confirm the same. Copying a tumblr address into memory, creates a new entry in TumbleThree. It creates 2 directories.
Ex. "~/my_site" and "~/my_site_2". If I download pictures etc. it lands in the my_site_2 directory.
This seems to be a new behaviour, not seen before. 
I would understand, if you had a directory like "~/my_first" before, have removed the blog and added the blog again.
So that a second directory "~/my_first_2" would be created and the previous content would not get overwritten.
Hope it makes sense.

**Comment by thomas694** [comment] 2021-11-13 16:44
The issue has been fixed and closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Closed by thomas694** 2021-11-13 16:44 UTC
