### ISSUE TITLE
Columns width keep resetting to minimum value

### ISSUE THREAD

**Issue by calves07** [TumblThreeApp/TumblThree#152] opened 2021-05-21 10:52 UTC
**Describe the bug**
Every time I open the app, all the columns have minimum depth so I always need to manually resize all the columns to be able to actually see the data.

**To Reproduce**
For me, I just need to close and reopen the app.

**Expected behavior**
I expect the column width to remain the same after restarting the app or at least default to the size that will allow the data to fit.

**Screenshots**

![image](https://user-images.githubusercontent.com/16237486/119126309-c7e50580-ba2a-11eb-926d-af80d780080b.png)

**Desktop (please complete the following information):**
 - TumblThree version: 1.5.2.151 (was not introduced by this version)
 - OS: Windows 10 Education N

**Comment by thomas694** [comment] 2021-05-21 14:56
Hello,
please have a look on your file settings.json (%LOCALAPPDATA%\TumblThree\Settings or local folder for portable mode). The part should look like:
```json
  "ColumnSettings": [
    {
      "Key": "Name",
      "Value": {
        "m_Item1": 0,
        "m_Item2": 180,
        "m_Item3": 0
      }
    },
```
What is the value of "m_Item2"?
Do your other TumblThree settings from the settings dialog persist on app restart, or are they reset too?

**Comment by calves07** [comment] 2021-05-21 15:08
Hi,

`What is the value of "m_Item2"?`
1 for all columns.

`Do your other TumblThree settings from the settings dialog persist on app restart, or are they reset too?`
Other settings persist.

**Comment by thomas694** [comment] 2021-05-21 16:02
[As before](https://github.com/TumblThreeApp/TumblThree/issues/112) this one is for first-timers-only. That means that we will only accept a PR for this one from someone who's never contributed to open source before. This one is particularly easy (but don't make that statement make you feel bad if you have a hard time with it, there's more to contributing to open source than changing lines of code, especially if it's your first time). We walk you through it if you need help. :-) Here are the steps to get a PR merged (see also our [guide](https://github.com/TumblThreeApp/TumblThree/blob/master/Contributing.md)).

When double-clicking on the column header to set it to the optimal width, the column width is reset on next app start. But when the column header is dragged with the mouse to its new width, the column width keeps the same after an app restart.

- [x] Create a fork of the repository
- [x] Clone it to your local disk and create a new branch (e.g. 152-column-width-keeps-resetting)
- [x] Look which view is dealing with the blog list. Where are the column widths set after start of the app? Where are they read for persisting them in the settings? What is the problem and how can it be solved?
- [x] Add your solution
- [x] Build the app and run it
- [x] Resize the column headers by both ways described in this issue
- [x] Close and restart the app again
- [x] Validate that your chosen column widths are retained
- [x] Commit your changes mentioning "issue #152" somewhere in your commit message title or description
- [x] Push your changes to your fork, create a PR, get merged, celebrate??

We are happy to support you if you need help.

**Comment by kartik727** [comment] 2021-05-21 18:37
Hi, I would like to work on this

**Comment by thomas694** [comment] 2021-05-21 20:39
Hi Kartik,
thanks for your interest to work on this issue. I'll assign it to you.

**Comment by thomas694** [comment] 2021-06-04 20:08
Hi,
if you are stuck or need any help, let me know.

**Comment by abikaram** [comment] 2021-06-04 21:03
Hello,
I would like to work on this issue. It's my first time contributing to open source.
thanks

**Comment by thomas694** [comment] 2021-06-04 21:43
Hello,
at the moment Kartik is working on it.
But you can keep an eye on it, if you like.

**Comment by kartik727** [comment] 2021-06-05 20:25
@thomas694  I am able to reproduce the bug and looks like when the column width is set using the double click, the width is not properly set in the settings JSON, and instead reset to 1 (which might be the default value), so perhaps the part responsible to send this variable is sending a null or invalid value in this case. But I don't know where this value is set (who writes to the json?) and I'm not sure what a 'view' means in this context from the instructions written above.

**Comment by thomas694** [comment] 2021-06-06 01:21
The global settings object is updated in the view model and written to file in the ModuleController. View in this context means "dialogs" or UI parts of the total window in this case, so the actual view in the TumblThree.Presentation project and its corresponding view model in TumblThree.Applications project. The json is only the storage, so I think it's going wrong somewhere before, the value written to the settings object is already not correct.

**Comment by thomas694** [comment] 2021-07-17 21:28
Hello,
how is the status? Do you get along with the code?

**Comment by thomas694** [comment] 2021-09-10 20:34
This issue is available again for new volunteers.

**Closed** 2022-12-09 20:41 UTC
Labels: bug, good first issue, beginner, first-timers-only
