### ISSUE TITLE
Cannot setup and download "Likes"

### ISSUE THREAD

**Issue by CFCeltic** [TumblThreeApp/TumblThree#182] opened 2021-11-05 15:58 UTC
When trying to add a Tumblr Blog entry for the "Likes", I receive an error message banner that states "Error 1: The blog already exists" I have created the "main" blog in TumblThree, and this downloads fine.  I have also deleted the "main" blog, and have tried to add the "Likes", and what is added is the main blog without the likes directory in the URL.  I am logged in to Tumblr through TumblThree

https://XXXXX.tumblr.com/Likes/ gets saved as https://XXXXX.tumblr.com

**To Reproduce**
1. Add blog https://XXXXX.tumblr.com
2. Try to add blog https://XXXXX.tumblr.com/likes/
3. See error

**To Reproduce**
Without main blog already added
1. Add blog https://XXXXX.tumblr.com/likes/
2. See that it is saved without the Likes directory

**Expected behavior**
Expect to be able to have both the main blog and the likes blog in the TumblThree UI

**Desktop (please complete the following information):**
 - TumblThree version: 2.4.1.210
 - OS: Win10 Pro

**Comment by thomas694** [comment] 2021-11-05 19:21
It's not a bug.

" **Liked/by and Likes backup/download:**

* A downloader for downloading "liked by" (e.g. https://www.tumblr.com/liked/by/wallpaperfx/) and "likes" (e.g. https://www.tumblr.com/likes) photos and videos instead of a tumblr blog (login required). 

"

**Comment by CFCeltic** [comment] 2021-11-06 02:29
Thomas, It might be helpful if you were a little more clear about what you are trying to say.  Are you trying to suggest/show me is that my URL is not correct, is that right? And that TumblThree does not support the URL format that I was trying?

If so, I will give that a try. Thanks

**Comment by thomas694** [comment] 2021-11-06 15:02
Hello Vance,

I was a bit in a hurry, so I just wrote it's not a bug/error and quoted from our main page (another place would be the Wiki) to show examples of the needed urls.
Yes, you need to use the correct url format:
https://wallpaperfx.tumblr.com/   for downloading the blog "wallpaperfx"
https://www.tumblr.com/liked/by/wallpaperfx/  for downloading this blog author's likes
but
https://www.tumblr.com/likes  would download your own likes, if you have made any in your account.

I hope it's more clear now. Anyway, you are welcome to support us and make a suggestion how we can rephrase the paragraph on the main page resp. wiki page in order to make it more clear to users/newbies.

Ok, as you already gave a hint in your update I just quickly did a short test to be sure, now I found out that Tumblr changed their data structures again and the Liked-By/Likes downloads are not working at the moment.
So it needs to be fixed in our next version in a couple of days (until then it's only possible to download normal blogs).

Of course, viewed from your side the outcome might look the same, but you brought to our attention that the "likes" downloads need changes again.
Thanks.
Thomas

**Comment by CFCeltic** [comment] 2021-11-06 15:24
Thanks Thomas, appreciate the reply and confirmation. I will give that a try as well.

As a long time software developer and now manager, I understand the need for feedback especially where functionality is concerned and is not behaving as expected. Sometimes it is a training issue, like my initial question, and other times there might be a problem. I would be glad to help with some of the wording if it will help make things more clear.

Thanks

**Comment by thomas694** [comment] 2021-11-22 09:50
The issue has been closed. You can still comment. Feel free to ask for reopening the issue if needed.

**Closed by thomas694** 2021-11-22 09:50 UTC
Labels: documentation
